import "./globals.css";
import { Nav } from "@src/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-4">
        <Nav />
        {children}
      </body>
    </html>
  );
}
