import "../globals.css";
import { Nav } from "@components";
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="m-4">
        <Nav />
        {children}
      </body>
    </html>
  );
}
